import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Wrappers from "@/components/wrappers";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrappers>{children}</Wrappers>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "YouCan-Hire",
  description: "Generated by create next app",
};
